services:
  db:
    container_name: mariadb-container
    image: mariadb:10.5
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: mdpyumiroot
      MYSQL_USER: yumi
      MYSQL_PASSWORD: mdpyumi
      MYSQL_DATABASE: pokedexdb
    ports:
      - "3306:3306"
      
  web:
    container_name: django-web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8042
    volumes:
      - ./pokedex_api:/app
    ports:
      - "8042:8042"
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: mdpyumiroot
      MYSQL_USER: yumi
      MYSQL_PASSWORD: mdpyumi
      MYSQL_DATABASE: pokedexdb
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: timo123
