# Generated by Django 4.2.11 on 2024-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$4LgMYIq6kLsGjZaThnkrH7$oQ/iMUrQ6iyvv0/ojWVw9H0kciefNSNndvzBu4biqRg=', max_length=255),
        ),
    ]
