# Generated by Django 4.2.11 on 2024-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_egggroup_items_location_move_pokemon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$52ZaXvdHSq3JSTReEx7fNg$E0DEKQGNIGfdZZJhhMJjIQ+ARIjSm1AJGyTtNv8as3Y=', max_length=255),
        ),
    ]
