# Generated by Django 4.2.11 on 2024-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$I5ZrfKdC6xkUYhItrd61JZ$YThTVVlbezEvLqGEshtAnFF7aTxD7bky4qOkA54mwvY=', max_length=255),
        ),
    ]
