# Generated by Django 4.2.11 on 2024-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_role_name_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$pUdjUyvANQ3PvSz4mNwGUk$COKAutAP4HBPPjQCSnkTkAxl2eF2tMYknT7YjRkd208=', max_length=255),
        ),
    ]
