# Generated by Django 4.2.11 on 2024-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_role_name_alter_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Z1Mhn07EmC2x5co8OHT4Jj$eG6+PIvnSUy9Mn0/FrbClSMPpKaCdfJpi+WpXLxGUO8=', max_length=255),
        ),
    ]
