# Generated by Django 4.2.11 on 2024-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_password_hash_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egggroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonegggroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonformgeneration',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonmove',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonstat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$J32gcVjMYa0eq71RV75iMt$JEacuMithBK6dxSua3A9zgUrYp0OSULpEX26bZLa/+k=', max_length=255),
        ),
    ]
