# Generated by Django 4.2.11 on 2024-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$pYHWpkSiXySlwQiBBVgLXC$Oe1+8VX6RXFDqfNn8yg1v/1v8LthsrRWRecgnvCX2Vo=', max_length=255),
        ),
    ]
