# Generated by Django 4.2.11 on 2024-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$n4sC0lbyBEGfIW5S3ZMX52$iHFmRYLjs2t4pa1ADBX7BV8q6qr3ZGeXdNo8a7mX5cM=', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
