# Generated by Django 4.2.11 on 2024-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_password_hash_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$wMtCdFLtLjI2YOa8SMxcKr$8+uubxBSz47wfI1FbQHMyGEHX7J5U2L+dYZKVmaheDo=', max_length=255),
        ),
    ]
