# Generated by Django 4.2.11 on 2024-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_password_hash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolePermission',
            new_name='RolePermissions',
        ),
        migrations.RenameModel(
            old_name='UserRole',
            new_name='UserRoles',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$KN1YfqcqgbW2rYFxXiipdO$lHU1yfMw6jagnZusfykHlW5NzMXTSqk90Y+S8wIiiv4=', max_length=255),
        ),
    ]
