# Generated by Django 4.2.11 on 2024-04-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userpokemon_alter_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$600000$FyztHMpzcHQcsvHsSojNpP$VTWPFlwL4LnkC9Ol4isM4W861VeARUhLI8p1qfFeA0g=', max_length=255),
        ),
    ]
